### ISSUE TITLE
Platform error 'sensor' from integration 'moon_phase' - Integration 'moon_phase' not found.

### ISSUE THREAD

**Issue by AnotherVisitor** [frlequ/moon-phase#1]
I followed your instructions, copied all files into /root/homeassistant/custom_components

```
total 16K    
-rw-r--r--    1 root     root          32 Jun  6 15:28 __init__.py
-rw-r--r--    1 root     root         306 Jun  6 15:28 manifest.json
-rw-r--r--    1 root     root        5.1K Jun  6 15:28 sensor.py
```

... I added 

```
sensor:
  - platform: moon_phase
```

... to the configuration.yaml

But if I check the configuration I get a configuration warning:

`Platform error 'sensor' from integration 'moon_phase' - Integration 'moon_phase' not found.`

Any idea what I did wrong?

**Comment by frlequ** [comment]
Did you copy whole directory to `custom_components` or just files?

**Comment by AnotherVisitor** [comment]
I created the `moon_phase` directory in the the `custom_components` then copied the files into it (`moon_phase`).

```
homeassistant cd custom_components 
➜  custom_components ls -l
total 20
drwxr-xr-x    5 root     root          4096 Jun 11 00:19 battery_notes
drwxr-xr-x    4 root     root          4096 May 16 17:11 dwd
drwxr-xr-x    3 root     root          4096 May 25 00:01 dwd_weather
drwxr-xr-x   10 root     root          4096 May 15 23:33 hacs
drwxr-xr-x    2 root     root          4096 Jun  6 15:32 moon_phase
➜  custom_components 
➜  custom_components cd moon_phase 
➜  moon_phase ls -l
total 16
-rw-r--r--    1 root     root            32 Jun  6 15:28 __init__.py
-rw-r--r--    1 root     root           306 Jun  6 15:28 manifest.json
-rw-r--r--    1 root     root          5265 Jun  6 15:28 sensor.py
➜  moon_phase 
```

**Comment by Blendi** [comment]
Hello,

I have exactly the same issue. I have downloaded and copied the 3 files into config\custom_components\moon_phase folder. I have mounted the /config file to my pc.

I added the line   - platform: moon_phase under sensor in configuration file and when I check it I have same warning.

Thing that I noticed is that the __init__.py file looks like it is empty, I see only these writing --> """The moon_phase component."""

Something is wrong, homeassistant somehow does not know about this new integration even thought the files are there.
![2024-07-08 11_31_06-Window](https://github.com/frlequ/moon-phase/assets/3333692/23a6a158-24da-42db-811e-957665d5b078)

Config file setup
![2024-07-08 11_41_48-Clipboard](https://github.com/frlequ/moon-phase/assets/3333692/76d0a94b-0691-47a8-903b-44e82ce58659)

Check unsuccessful
![2024-07-08 11_42_05-Window](https://github.com/frlequ/moon-phase/assets/3333692/f47325b0-ad0c-4123-a365-5bf9aa7e35bd)

**Comment by RevAntun** [comment]
Hi!
Me 2 the same issue.

Update: think the manifest.json make some troubles, maybe ...

**Comment by bhouseski** [comment]
also have the same issue as above.

**Comment by frlequ** [comment]
Sorry guys for the late reply. There was a bug in `manifest.json` file, please update it to the latest version.

![image](https://github.com/user-attachments/assets/7171432f-325e-4dbc-a323-c0597f42f551)

**Comment by bhouseski** [comment]
working now.

question, is there a way to change to format of the date/time?  specifically, I would like to display the moon rise/ set times as an AM/PM time only (no date).

**Comment by RevAntun** [comment]
> Sorry guys for the late reply. There was a bug in `manifest.json` file, please update it to the latest version.
> 
> ![image](https://private-user-images.githubusercontent.com/121799877/352709844-7171432f-325e-4dbc-a323-c0597f42f551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTU1NjIsIm5iZiI6MTcyMjExNTI2MiwicGF0aCI6Ii8xMjE3OTk4NzcvMzUyNzA5ODQ0LTcxNzE0MzJmLTMyNWUtNGRiYy1hMzIzLWMwNTk3ZjQyZjU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMTIxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzFmNTA0M2NhZDBhYzQxYzVjZTRmZmM1Yjc4NDQ5OTdiY2JjYjRiMjNlMjM0MDI2NmU3ZmFmZGFiNWVlODI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jaR2YriR5pNjOqVM2bDUDC-V653QcmSecoEvtwQz_Hg)

thx !

**Comment by AnotherVisitor** [comment]
Thank you.
This solved the issue.
